### ISSUE TITLE
why i cant use it as digitizer (via bluetooth) with the pen and can't draw in gimp 

### ISSUE THREAD

**Issue by 243750496** [jbedo/boogiesync-tablet#8] opened 2016-11-21 13:07 UTC
cc@CC:~/boogiesync-tablet-master$ python3 blue.py 00:17:E9:88:AA:D2
Searching for boogie board sync on 00:17:E9:88:AA:D2
connecting to "HID over SPP" on 00:17:E9:88:AA:D2
connected

but why i cant see it in digitizer mode with the pen and can't draw in gimp 
do i need some other software to install???

**Comment by jbedo** [comment] 2016-11-22 06:18
Does the mouse cursor move at all when moving the pen around?

**Comment by jbedo** [comment] 2016-11-22 06:23
Ah I think this might be a duplicate of #1. Can you try via usb and see if that works? If it does work, can you then try bluetooth afterwards without resetting the boogie board to see if there's any change?

**Comment by 243750496** [comment] 2016-11-23 06:52
Q1:Does the mouse cursor move at all when moving the pen around?
AS:no
Q2:
AS:
`cc@CC:~/boogiesync-tablet-master$ sudo python3 usb-driver.py
[sudo] password for cc: 
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
Payload sent
`
**Traceback (most recent call last):
  File "usb-driver.py", line 57, in <module>
    ui = UInput(cap, name='boogie-board-sync-pen')
  File "/usr/local/lib/python3.5/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
OSError: [Errno 22] Invalid argument**

cc@CC:~/boogiesync-tablet-master$ sudo python3 usb-driver.py
Payload sent
Traceback (most recent call last):
  File "usb-driver.py", line 57, in <module>
    ui = UInput(cap, name='boogie-board-sync-pen')
  File "/usr/local/lib/python3.5/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
OSError: [Errno 22] Invalid argument

**Comment by jbedo** [comment] 2016-11-23 07:59
Believe it or not that looks like it mostly worked. It did succeed in sending the payload and knocking the tablet into digitiser mode, but looks like it then died when creating an input device because evdev isn't working properly on your installation. Not sure what to suggest here, I think the problem lies in evdev.

You'll probably find the bluetooth version works after the usb one knocks it into digitiser mode, but it'll probably also die in evdev.

**Comment by 243750496** [comment] 2016-11-23 09:20
how can evdev get the payload transfer working and knocking into digitiser mode 
Q:by upgrade to newest version of evdev?(i used pip3 to install evdev's pre version shall i need to compile from source?)

**Comment by jbedo** [comment] 2016-11-25 02:54
Maybe try your distro's evdev package?

**Comment by 243750496** [comment] 2016-11-25 23:42
sloved with such steps (but dont know witch one sloved the problem maybe the official evdev not the pip one)
sudo apt-get install libbluetooth-dev
sudo add-apt-repository ppa:bluetooth/ppa
sudo add-apt-repository ppa:cwayne18/fitbit
sudo apt-get install python-evdev python-bluez python3-evdev python-pyusb
sudo apt-get install bluetooth libbluetooth-dev 
sudo pip3 install pyusb
sudo pip3 install pybluez

and get 
`payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
Payload sent`
while the pen moved the curser moved (while the usb connected but bluetooth still not moved with connected) but seems in gimp there's no pressure , 
how to slove that???
**Q1:under bluetooth connected curseor still not moved with pen moved
Q2:with usb connected the pen in gimp there's no pressure ,**

**Comment by 243750496** [comment] 2016-11-26 00:00
![1](https://cloud.githubusercontent.com/assets/6311930/20636770/41e8842a-b3ae-11e6-83c3-272a32419010.png)
sloved the Q2
but Q1 Still not sloved
**Q1:under bluetooth connected curseor still not moved with pen moved**

**Comment by jbedo** [comment] 2016-11-27 22:55
Does the bluetooth driver ever say "good response"? Probably it's failing to knock the tablet into digitiser mode. I'll see if some sort of hacky loop works, like in the usb version.

**Comment by 243750496** [comment] 2016-11-28 02:04
`cc@CC:~/boogiesync-tablet-master$ python3 blue.py 00:17:E9:88:AA:D2
Searching for boogie board sync on 00:17:E9:88:AA:D2
connecting to "HID over SPP" on 00:17:E9:88:AA:D2
connected
`
AS:NO good response in terminal show up , that's what all i get .
if i use python not python3 i will get those (with good response and get an error and breaked out):
`cc@CC:~/boogiesync-tablet-master$ python blue.py 00:17:E9:88:AA:D2
Searching for boogie board sync on 00:17:E9:88:AA:D2
connecting to "HID over SPP" on 00:17:E9:88:AA:D2
connected
good response
Traceback (most recent call last):
  File "blue.py", line 69, in <module>
    ui = UInput(cap, name='boogie-board-sync')
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument
`

**Comment by jbedo** [comment] 2016-11-28 20:48
ok that's pretty interesting, because with python 2 it seems to send the payload and get a good response, but die trying to create a uinput device. Are you using python 2 or 3 with usb?

**Comment by 243750496** [comment] 2016-11-28 21:39
@jbedo 

**cc@CC:~/boogiesync-tablet-master$ sudo python usb-driver.py**
[sudo] password for cc: 
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
Payload sent
Traceback (most recent call last):
  File "usb-driver.py", line 57, in <module>
    ui = UInput(cap, name='boogie-board-sync-pen')
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
**IOError: [Errno 22] Invalid argument
cc@CC:~/boogiesync-tablet-master$ sudo python3 usb-driver.py
Payload sent**


with python3 i curser moved while pen moved , btw Q: Do the sudo is a must while trying to connect by using usb Q2: what about bluetooth(why bluetooth doesn't need sudo command???)

**Closed as completed** 2016-12-11 00:52 UTC
